//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ugani_Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class BANAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BANAN()
        {
            this.CHITIETDATBANs = new HashSet<CHITIETDATBAN>();
        }
        [Required(ErrorMessage ="Vui lòng nhập mã bàn!"),RegularExpression("^[a-zA-Z]*$", ErrorMessage = "Mã bàn là một chuỗi ký tự!")]
        [DisplayName("Mã bàn")]
        public string MABAN { get; set; }
        [Required(ErrorMessage = "Vui lòng chọn loại bàn!")]
        [DisplayName("Loại bàn")]
        public int MALOAIBAN { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập số lượng ghế!")]
        [DisplayName("Số lượng ghế"),Range(1, 10, ErrorMessage = "Chỉ cho phép nhập tối đa 10 ghế!")]
        public Nullable<byte> SOGHE { get; set; }
    
        public virtual LOAIBAN LOAIBAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDATBAN> CHITIETDATBANs { get; set; }
    }
}
