//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ugani_Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class CHITIETDATBAN
    {
        public string MAKH { get; set; }
        public string MABAN { get; set; }
        public Nullable<System.DateTime> NGAYDAT { get; set; }
        public Nullable<System.TimeSpan> GIODATBAN { get; set; }
        public Nullable<System.TimeSpan> GIOTRABAN { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual BANAN BANAN { get; set; }
    }
}
