//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ugani_Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public int MAHD { get; set; }
        public string MAKH { get; set; }
        public Nullable<System.DateTime> NGAYDATCOC { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
        public Nullable<decimal> TIENCOC { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
