//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ugani_Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class HOADON
    {
        [DisplayName("Tên khách hàng")]
        public string MAKH { get; set; }
        [DisplayName("Ngày đặt cọc"), DisplayFormat( DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> NGAYDATCOC { get; set; }
        [DisplayName("Tổng tiền")]
        public Nullable<decimal> TONGTIEN { get ; set; }
        [DisplayName("Tiền đã cọc")]
        public Nullable<decimal> TIENCOC { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        //DisplayFormat(DataFormatString = "{0:0,0}", ApplyFormatInEditMode = true)
    }
}
