//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ugani_Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MONAN()
        {
            this.CHITIETDATMONANs = new HashSet<CHITIETDATMONAN>();
        }
    
        public int MAMONAN { get; set; }
        public int MALOAIMON { get; set; }
        public string TENMONAN { get; set; }
        public string HINHANH { get; set; }
        public Nullable<decimal> DONGIA { get; set; }
        public string DVT { get; set; }
    
        public virtual LOAIMON LOAIMON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDATMONAN> CHITIETDATMONANs { get; set; }
    }
}
