//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ugani_Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class MONAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MONAN()
        {
            this.CHITIETDATMONANs = new HashSet<CHITIETDATMONAN>();
        }

        public int MAMONAN { get; set; }
        [DisplayName("Loại món"), Required(ErrorMessage = "Vui lòng chọn loại món!")]
        public int MALOAIMON { get; set; }
        [DisplayName("Tên món"), Required(ErrorMessage = "Vui lòng nhập tên món!")]
        public string TENMONAN { get; set; }
        [DisplayName("Hình ảnh"),Required(ErrorMessage = "Vui lòng thêm hình ảnh!")]
        public string HINHANH { get; set; }
        [DisplayName("Đơn giá"),Required(ErrorMessage = "Vui lòng nhập đơn giá!")]
        public Nullable<decimal> DONGIA { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập đơn vị tính!")]
        [DisplayName("Đơn vị tính"), RegularExpression("^[a-zA-Z]*$", ErrorMessage = "Đơn giá là một chuỗi ký tự!")]
        public string DVT { get; set; }
    
        public virtual LOAIMON LOAIMON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDATMONAN> CHITIETDATMONANs { get; set; }
    }
}
